import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const exportToExcel = (data, filename = 'export') => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  saveAs(blob, `${filename}.xlsx`);
};

export const exportToCSV = (data, filename = 'export') => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csv = XLSX.utils.sheet_to_csv(worksheet);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, `${filename}.csv`);
};

export const exportToPDF = (data, columns, title, filename = 'export') => {
  const doc = new jsPDF();
  
  // Branded header band
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 24, 'F');
  doc.setTextColor(255);
  doc.setFontSize(13);
  doc.text('Rent Management System', 14, 11);
  doc.setFontSize(17);
  doc.text(title || 'Report', 14, 19);

  // Meta row under header
  const metaY = 30;
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, metaY);
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(`Total records: ${data.length}`, 14, metaY + 6);
  
  // Prepare table data
  const tableData = data.map(row => 
    columns.map(col => {
      const value = row[col.key];
      if (value === null || value === undefined) return '';
      if (typeof value === 'object' && value !== null) {
        if (col.format) return col.format(value);
        return JSON.stringify(value);
      }
      if (col.format) return col.format(value);
      return String(value);
    })
  );
  
  // Main data table
  autoTable(doc, {
    head: [columns.map(col => col.label)],
    body: tableData,
    startY: metaY + 14,
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      textColor: [31, 41, 55]
    },
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    }
  });
  
  // Footer with timestamp on every page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    const footerY = doc.internal.pageSize.getHeight() - 10;
    doc.text(
      `Generated by Rent Management System • ${new Date().toLocaleString()}`,
      14,
      footerY
    );
    const pageLabel = `Page ${i} of ${pageCount}`;
    const textWidth = doc.getTextWidth(pageLabel);
    doc.text(pageLabel, doc.internal.pageSize.getWidth() - 14 - textWidth, footerY);
  }

  doc.save(`${filename}.pdf`);
};

export const exportPaymentsToPDF = (payments, filename = 'payments-report') => {
  const columns = [
    { key: 'paymentDate', label: 'Date', format: (val) => val ? new Date(val).toLocaleDateString() : '' },
    { key: 'tenant', label: 'Tenant', format: (val) => val ? `${val.firstName} ${val.lastName}` : 'N/A' },
    { key: 'house', label: 'House', format: (val) => val ? val.houseNumber : 'N/A' },
    { key: 'amount', label: 'Amount', format: (val) => `KSh ${(val || 0).toLocaleString()}` },
    { key: 'status', label: 'Status' },
    { key: 'paymentMethod', label: 'Method' }
  ];
  
  exportToPDF(payments, columns, 'Payments Report', filename);
};

export const exportTenantsToPDF = (tenants, filename = 'tenants-report') => {
  const columns = [
    { key: 'firstName', label: 'First Name' },
    { key: 'lastName', label: 'Last Name' },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'house', label: 'House', format: (val) => val ? val.houseNumber : 'Not Assigned' },
    { key: 'status', label: 'Status' }
  ];
  
  exportToPDF(tenants, columns, 'Tenants Report', filename);
};

